reidmorrison/semantic_logger

lib/semantic_logger/appender/splunk.rb
test/appender_splunk_test.rb

Hello,
In order to ease development with this library, I've added a default for the `index` parameter in the Splunk appender. Since a default install of Splunk comes with the `main` index, this will just send the logs there by default.
I'm curious what you think. Let me know
Thanks

Add default index for Splunk appender

---

lib/semantic_logger/appender/base.rb

Changes the default formatter to only print the log payload data if it is both present (not null) and non-empty. This prevents `-- {}` from appearing in log messages, though there may be a use case for this for some users.

only print the payload if it is both non-null and non-empty

---

Rakefile
lib/semantic_logger/appender/base.rb
lib/semantic_logger/appender/syslog.rb
lib/semantic_logger/base.rb
test/appender/file_test.rb
test/appender/splunk_test.rb

Added logging for nested exceptions for file and syslog appenders.  Bugsnag already handles this (I know because I stole there code).  Didn't address for mongodb, new_relic or splunk. 
Run all tests from rake.
Some test fixes.

Handle nested exceptions

---

Gemfile
lib/semantic_logger.rb
lib/semantic_logger/appender/sentry.rb
test/appender/sentry_test.rb

We were missing an appender for Sentry and thought it is better to share the appender in case someone else needs it. This is just a first version of the appender and the intention with the pull request at this stage is to get some feedback.
Not sure why they call it sentry-raven as I find it very confusing so I decided to keep just sentry. Could easily be changed should anyone wish for it.

Adds appender for Sentry (Raven)

---

lib/semantic_logger/appender/graylog.rb

Graylog was unable to parse current payload with this error:
`MapperParsingException[failed to parse [duration]]`
http://docs.graylog.org/en/2.1/pages/indexer_failures.html
It has a duration field of type number.
Here is my suggestion for renaming this field just for graylog

Fix graylog duration parsing error

---

lib/semantic_logger/appender/graylog.rb
test/appender/graylog_test.rb

https://github.com/rocketjob/semantic_logger/issues/57

fix graylog appender if logger called only with exception object

---

lib/semantic_logger/appender/elasticsearch.rb
test/appender/elasticsearch_test.rb

In some cases, passing the url only is insufficient. This adds the ability to pass the full range of arguments directly into the Elasticsearch Client in a backwards compatible way.
For tests, I just duplicated the tests and nested them accordingly to ensure there were no breaking changes.
Please see: https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-transport/lib/elasticsearch/transport/client.rb#L34-L84

Support passing all Elasticsearch::Client args

---

lib/semantic_logger/semantic_logger.rb

I have a use case where I'd like to add a log tag but don't have a block to operate on, so I've added `push_named_tags` and `pop_named_tags` to mirror the methods available for regular tags.
cc @smudge

Add push and pop for named tags

---

lib/semantic_logger/appender/elasticsearch.rb
test/appender/elasticsearch_test.rb

Elasticsearch change the bulk API (At least after version 6.0. Not sure on 5.x) so that we can't omit the index name even if it is the same as the previous one. Otherwise the bulk operation will always fail.

Fix Elasticsearch bulk bugs

---

lib/semantic_logger/appender/sentry.rb

If the formatter privides a user entry or tags entry, it will be now passed next to the 'extra' context to sentry.

Sentry appender can now define user context and tags context

---

lib/semantic_logger/formatters/syslog.rb
lib/semantic_logger/formatters/syslog_cee.rb

Just small typo fixes for Syslog formatters exception messages.
CI skipped because no need to run it

Fix typo for syslog exception messages (on LoadError)

---

lib/semantic_logger/semantic_logger.rb
test/semantic_logger_test.rb

As described in #97, trying to use `SemanticLogger.on_log` produces the following error:
```
/usr/local/bundle/gems/semantic_logger-4.2.0/lib/semantic_logger/semantic_logger.rb:226:in `on_log': undefined method `on_log' for #<SemanticLogger::Appender::Async:0x00000000033fb328> (NoMethodError)
```

Fix SemanticLogger.on_log

---

lib/semantic_logger/appender/syslog.rb

Fixes https://github.com/rocketjob/rails_semantic_logger/issues/52

Now syslog appender calls ::Syslog.reopen if it is already opened.

---

docs/rails.md

It's very easy to misread `backtrace_level` as somewhat akin to a log level 
configuration and end up using it in production without understanding how 
much of a performance issue it will cause.
I'm proposing this documentation change as a first step but I really think some 
sort of warning should be printing to the logs if this setting isn't set to a very 
high log level value like `:fatal`/`4` in the production environment.
We had this mistakenly set to `:info` in production and the allocations and memory 
growth/leak were astounding.

Emphasize risk of backtrace_level in production

---

.travis.yml

Bumps the Travis Ruby versions for JRuby 9.2.0.0 and Ruby 2.6.0-preview2.

Update Travis Ruby versions

---

docs/_layouts/default.html

This allows browsers to accept the fonts from Google by default.
Just a tiny change to load fonts as https because my browser is blocking the mixed content. You can see this working as expected at: https://qstearns.github.io/semantic_logger/

Load Fonts by https

---

lib/semantic_logger/appender/splunk.rb
lib/semantic_logger/appender/splunk_http.rb

`source_type` should actually be `sourcetype`
This causes some versions of Splunk and Splunk Cloud to return a 400 Bad
Request with response `{"text":"No data","code":5}` and throw a EOF
Error
See <http://dev.splunk.com/view/event-collector/SP-CAAAE6P#meta> for
more info

Splunk/SplunkHTTP Appenders: Fix message metadata format

---

lib/semantic_logger/base.rb
test/logger_test.rb

This fixes issue #119
SemanticLogger::Logging has no access to `#named_tags` found on `SemanticLogger`.

Make #named_tags available on SemanticLogger::Logger

---

lib/semantic_logger/formatters/base.rb
lib/semantic_logger/formatters/color.rb
lib/semantic_logger/formatters/json.rb
lib/semantic_logger/formatters/raw.rb
lib/semantic_logger/formatters/signalfx.rb
lib/semantic_logger/log.rb
test/formatters/default_test.rb

Part of rocketjob/semantic_logger#122
There are some log parsing tools that aren't happy parsing microsecond
logs, and this makes work-around easier when you can't modify them.

Allow precision to be specified for formatters

---

.travis.yml

This pull request updates the Travis configuration to test against Ruby 2.6.0. Now that Ruby 2.6.0 is in a stable release, we should test against it. I also added `ruby-head` to the matrix as an allowed failure. This should help identify issues ahead of time. If you would like me to remove it, just let me know.
P.S. We just upgraded to Ruby 2.6.0 and are having a few difficulties that appear to be related to semantic logger. I wanted to push this through first before I opened an issue.

Test against Ruby 2.6.0

---

.gitignore
Gemfile
lib/semantic_logger/appender.rb
lib/semantic_logger/appender/rabbitmq.rb
test/appender/fake_bunny.rb
test/appender/mongodb_test.rb
test/appender/rabbitmq_test.rb

Hi there,
Thank you for developing and maintaining such interesting tool!
I would like to adds support for streaming logs to RabbitMQ broker.
I've created and a tested a new appender called `SemanticLogger::Appender::Rabbitmq` and updated the documentation.
Usage:
~~~ruby
SemanticLogger.add_appender(
appender:      :rabbitmq,
queue_name:    'semantic_logger', 
rabbitmq_host: 'localhost',
username:      'the-username',
password:      'the-password',
)
~~~
Please let me know if I am missing anything.
Thank you,
Fabio

Add RabbitMQ appender

---

lib/semantic_logger/appenders.rb

Fix 'NameError' always raised and logged by Appenders#close, due to wrong access to an unknown variable when deleting an appender
- `Appenders#close` has been modified, so that it now correctly removes each appender, without causing a `NameError` exception to be logged out.

Fix 'NameError' always raised and logged by Appenders#close

---

lib/semantic_logger/appender/bugsnag.rb
lib/semantic_logger/appender/elasticsearch.rb
lib/semantic_logger/appender/graylog.rb
lib/semantic_logger/appender/honeybadger.rb
lib/semantic_logger/appender/kafka.rb
lib/semantic_logger/appender/mongodb.rb
lib/semantic_logger/appender/new_relic.rb
lib/semantic_logger/appender/rabbitmq.rb
lib/semantic_logger/appender/sentry.rb
lib/semantic_logger/appender/splunk.rb
lib/semantic_logger/appender/syslog.rb
lib/semantic_logger/appender/tcp.rb
lib/semantic_logger/formatters/syslog.rb
lib/semantic_logger/formatters/syslog_cee.rb
lib/semantic_logger/metric/new_relic.rb
lib/semantic_logger/metric/statsd.rb

Fixes #138
Fixes sorbet/sorbet#1820
It's a best practice to re-raise a LoadError exception when catching a
LoadError exception, so that scripts can attempt to be resilient in the
face of a LoadError. Having to swallow all RuntimeExceptions is the
alternative, and it often makes things more brittle, rather than less.

Always re-raise with LoadError

---

docs/rails.md

None
Replacing existing loggers of DelayedJob is already supported in following PRs.
https://github.com/rocketjob/rails_semantic_logger/pull/56
https://github.com/rocketjob/rails_semantic_logger/pull/65
So, I've added 'DelayedJob' to "Replacing Existing loggers" section.

[doc] Add DelayedJob to "Replacing Existing loggers"

---

docs/metrics.md

creating the custom subscriber as described in this doc blows up on SemanticLogger#on_metric for the method not existing
SemanticLogger#on_log provides the desired output
better double check me on whether it's also an appropriate change in the New Relic and Statsd examples

remove references to nonexistent #on_metric

---

CHANGELOG.md

refs https://github.com/rocketjob/semantic_logger/issues/146#issuecomment-590521234
* First step/draft at "backporting" changelog updates
#146 
Changelog 4.6.x backports first step (draft)

Updated changelog with 4.6.x changes

---

lib/semantic_logger/log.rb
test/measure_test.rb

#146
restores SemanticLogger::Log.to_h method

refs #146 restore SemanticLogger::Log.to_h

---

CHANGELOG.md
lib/semantic_logger/logger.rb

When code in on_log raises an exception, it is rescued by this block which errors because it calls .processor on self.class which is "Class" rather than self which is "Logger"

Fix error in on_log exception handling

---

CHANGELOG.md
lib/semantic_logger/appender/splunk_http.rb

`environment` is not a valid root key for the Splunk HTTP Event
Collector. Including it results in a response code of `400` and a JSON
response body of `{"text":"No data","code":5}`.
This PR also updates the URL for the documentation since it has changed.

Fix SplunkHttp appender

---

CHANGELOG.md
docs/appenders.md
lib/semantic_logger/appender/syslog.rb
lib/semantic_logger/formatters/syslog.rb
lib/semantic_logger/formatters/syslog_cee.rb

Allow to update packet size to desired number or default it to 1024
Instead of using the `.to_s` we use the `assemble` method to set the size.

Set packet size for syslog

---

CHANGELOG.md
lib/semantic_logger/appender/splunk_http.rb
test/appender/splunk_http_test.rb

This change removes the `host` field from the splunk event. This makes sense because the host is already sent to splunk in the request using the `host` field. This removes duplicate information from splunk and makes it idiomatic. For example:
```json
{
"source": "Semantic Logger",
"host": "my-hostname",
"time": 1595506676.082487,
"event": {
"application": "Semantic Logger",
"environment": "test",
"level": "info",
"level_index": 2,
"pid": 90292,
"thread": "3180",
"name": "SemanticLogger::Appender::SplunkHttp",
"message": "AppenderSplunkHttpTest log message",
"payload": {
"key1": 1,
"key2": "a"
}
}
}
```
```json
{
"source": "Semantic Logger",
"host": "my-hostname",
"time": 1595506779.097824,
"event": {
"host": "my-hostname",
"application": "Semantic Logger",
"environment": "test",
"level": …
```

Do not include host field in splunk event

---

docs/forking.md

Added information about setting up Rails Minitest with Semantic Logger
If you use default testing framework in Rails and parallelize tests with processes, you will get no logs unless `SemanticLogger.reopen` will be added to test case base class

Add info about setting up logger with parallel Rails Minitest

---

CHANGELOG.md
lib/semantic_logger/formatters.rb
lib/semantic_logger/formatters/logfmt.rb
test/formatters/logfmt_test.rb

None
added :)
In this pr:
- Add Logfmt formatter to be used. Logfmt is plenty used on the industry to easily parse and write logs. We are currently using this approach in production

Add Logftm formatter

---

CHANGELOG.md
lib/semantic_logger/loggable.rb

```
$ RUBYOPT='-w' bundle exec rspec
…   
…/semantic_logger-4.8.1/lib/semantic_logger/loggable.rb:37: warning: method redefined; discarding old logger
…/activerecord-6.1.4/lib/active_record/core.rb:20: warning: previous definition of logger was here
…/semantic_logger-4.8.1/lib/semantic_logger/loggable.rb:42: warning: method redefined; discarding old logger=
…/activerecord-6.1.4/lib/active_record/core.rb:20: warning: previous definition of logger= was here
…/semantic_logger-4.8.1/lib/semantic_logger/loggable.rb:47: warning: method redefined; discarding old logger
…/activerecord-6.1.4/lib/active_record/core.rb:20: warning: previous definition of logger was here
…/semantic_logger-4.8.1/lib/semantic_logger/loggable.rb:37: warning: method redefined; discarding old logger …
```

Silence method redifinition warnings whe Rails is used

---

CHANGELOG.md
docs/index.md
docs/rails.md

This replaces the Travis CI configuration, now a 404.

[docs] Link to GitHub Actions CI config

---

lib/semantic_logger/formatters/base.rb
test/appender/elasticsearch_http_test.rb

I'm actually not sure how to put it in the changelog.
This was actually not a problem with tests, but actual bug in the implementation of elasticsearch appender. This was due to the fact that `Time#utc` method, used in raw formatter, which is in turn used by ES appender, mutates the `Time` object in-place. See:
```
irb(main):001:0* t = Time.now
=> 2021-10-13 01:25:20.920377865 +0200
irb(main):002:0> t.utc
=> 2021-10-12 23:25:20.920377865 UTC
irb(main):003:0> t
=> 2021-10-12 23:25:20.920377865 UTC
```
The fix is to force the formatter to operate on a duplicate of the `Time` object, so actual time in log entry is not mutated.

Fix inconsistencies in timezone handling for elasticsearch appender

---

CHANGELOG.md
docs/appenders.md
lib/semantic_logger/appender/elasticsearch.rb
test/appender/elasticsearch_test.rb

Support for elastic data-streams, see: https://www.elastic.co/guide/en/elasticsearch/reference/master/data-streams.html
Data streams are slightly different to regular indexes:
1. They only support `create` operations, so we change the `index` operation to `create` operation, i.e.
from this:
```
PUT _bulk
{"index": {"_index" => "index-name", "_type": "doc"}}
{ "timestamp": "2099-05-06T16:21:15.000Z", "message": "192.0.2.42 - - [06/May/2099:16:21:15 +0000] \"GET /images/bg.jpg HTTP/1.0\" 200 24736" }
```
to this:
```
PUT my-data-stream/_bulk
{ "create":{ } }
{ "@timestamp": "2099-05-06T16:21:15.000Z", "message": "192.0.2.42 - - [06/May/2099:16:21:15 +0000] \"GET /images/bg.jpg HTTP/1.0\" 200 24736" }
```
When we remove the `index` operation, we still need to tell the API the name of the …

Add support for elastic data-streams

---

CHANGELOG.md
lib/semantic_logger/base.rb
test/logger_test.rb

[Rails::Rack::Logger](https://github.com/rails/rails/blob/main/railties/lib/rails/rack/logger.rb) and [RailsSemanticLogger::Rack::Logger](https://github.com/reidmorrison/rails_semantic_logger/blob/master/lib/rails_semantic_logger/rack/logger.rb) can pass tags as an array in a single argument to `SemanticLogger::Base#tagged`. `SemanticLogger` casts this array to string. I fixed this behavior: unpack tags instead of casting to string.

Unpack array of tags in `tagged` method

---

CHANGELOG.md
docs/log_struct.md
docs/rails.md
lib/semantic_logger/formatters/logfmt.rb
lib/semantic_logger/semantic_logger.rb
test/formatters/logfmt_test.rb

Fixes https://github.com/reidmorrison/semantic_logger/issues/183
Includes `tags` and `named_tags` in logfmt formatted messages. 
```ruby
```
This also fixes an issue were the provided `time_key` was not used in the formatted log record. 

feat: Add tags to logfmt formatter output

---

CHANGELOG.md
lib/semantic_logger/appender/async_batch.rb

When `flush` is called on a `AsyncBatch` appender `batch` is called
after `process_message` has finished (which handles the `flush` call).
This means that when `flush` returns the log messages are not actually
written yet and if the process exits at this point the logs are lost.
This was observed to lose log messages in an AWS Lambda environment.

Fix `flush` on `AsyncBatch` appender

---

lib/semantic_logger/appender/kafka.rb

add passthru option for use system ssl certs for kafka writer
Add passthru for system certs for the kafka log writer

add kafka client option to use system SSL settings

---

CHANGELOG.md
lib/semantic_logger/appender/kafka.rb

- add required_acks flag passthru to the ruby-kafka driver
add another passthru to the ruby-kafka driver to set required_acks.  default to 1

Add required_acks passthru to ruby-kafka

---

CHANGELOG.md
lib/semantic_logger/appender/async.rb

I met ``NoMethodError: undefined method `kill' for nil:NilClass`` in `SemanticLogger.reopen`.
I think [`@thread = nil`](https://github.com/reidmorrison/semantic_logger/blob/8a1650ac90db653849b3082946e02db5c8f6cdd3/lib/semantic_logger/appender/async.rb#L138) can happen between `@thread&.alive?` and `@thread.kill` of [this line](https://github.com/reidmorrison/semantic_logger/blob/8a1650ac90db653849b3082946e02db5c8f6cdd3/lib/semantic_logger/appender/async.rb#L62).

Fix a race condition in SemanticLogger.reopen

---

CHANGELOG.md
lib/semantic_logger/formatters/logfmt.rb
test/formatters/logfmt_test.rb

Some objects, like hashes and arrays can be casted to valid json objects. Because of that they were not quoted correctly.
no issue
* The Logfmt formatter can now parse Hashes and Arrays correctly.
* The Logfmt formatter can now parse Hashes and Arrays correctly.

fix Logfmt#flatten_log

---

CHANGELOG.md
lib/semantic_logger/appender/sentry_ruby.rb

Calls Sentry.init inside sentry_ruby appender only if it is not initialized
These changes allow developers to use their own sentry initializer like this: 
```ruby
Sentry.init do |config|
config.excluded_exceptions += %w[AwesomeCustomError]
config.logger = SemanticLogger[::Sentry]
config.traces_sample_rate = 1.0
end
```

Initialize sentry only if it is not initialized (fixes #218)

---

CHANGELOG.md
lib/semantic_logger/semantic_logger.rb

- Fixed log level signal handler to include fatal and error levels.
The log level changer signal handling was omitting the :fatal and :error levels from the cycle of levels. At first I thought it appeared that way only because the log method used was `warn`, but when I used STDERR to log the changes I still did not see `:fatal` and `:warn`.
The problem was that the code assumed that `:error` was the highest level, and then subtracted 1 from its level. This code change uses the index boundaries of the `LEVELS` array to guarantee that the correct sequence of levels is used.
For an easy way to illustrate the problem, check out https://gist.github.com/keithrbennett/006c10128ee3a2f37da98b7f013d3951, which uses stderr output instead of the logger.
By submitting this pull request, I confirm that …

Fix log level signal handler to include :fatal and :error levels.

---

CHANGELOG.md
lib/semantic_logger/appender/http.rb
test/appender/http_test.rb

In certain configurations you may already need to have the http_proxy env var set but need a different proxy setup for an HTTP appender - or need the HTTP appender to not utilize the environment configuration.
- New Feature: Ability to directly set proxy for `SemanticLogger::Appender::Http`
- Updated `SemanticLogger::Appender::Http#initialize` to take a `proxy_url` parameter that defaults to `:ENV`.  This value is used internally by `Net::HTTP` to specify that the proxy configuration should be read from the environment, so this should retain the existing behaviour.  Passing in a properly formatted URL (including username/password if necessary) will directly specify the proxy server to use for the appender.  Passing in `nil` will specifiy that the underlying `Net::HTTP` connection **should …

Add support for setting the proxy directly for the HTTP appender.

---

lib/semantic_logger/formatters.rb
lib/semantic_logger/formatters/syslog_cee.rb
test/formatters/syslog_cee_test.rb

None
* Added missing SyslogCee into SemanticLogger::Formatters module
* Added test for SemanticLogger::Formatters::SyslogCee
After testing the Syslog appender I found a bug that raises exceptions:
```
/usr/local/bundle/gems/semantic_logger-4.11.0/lib/semantic_logger/utils.rb:8:in `const_get': uninitialized constant SemanticLogger::Formatters::SyslogCee (NameError)
Object.const_get(klass)
^^^^^^^^^^
```
It raises when I tried to use SyslogCee formatter
```
SemanticLogger.add_appender(appender: :syslog, formatter: :syslog_cee)
```
There is a simple missing SyslogCee autoload in the SemanticLogger::Formatters module. This Pull Request fixes that issue.

Add missing autoload for syslog_cee formatter

---

CHANGELOG.md
lib/semantic_logger/test/minitest.rb

Thanks for adding these test helpers, they've made testing functionality very easy. I ran into a couple of issues where tests would pass when I didn't expect them to which led me to raise this PR.
If the payload being tested does not contain the key you're checking for then the test will pass. The expectation is that the test should fail and report what was found in the payload instead.
The below changes do the following:
- Only assert nil when the `expected_value` is nil instead of the actual value. 
- Add the event payload to the failing test output. The log message does not contain this information and makes it difficult to debug.

Bug: Missing key in logging payload causes tests to pass in Minitest helper

---

CHANGELOG.md
README.md
docs/centralized_logging.md
lib/semantic_logger/appender.rb
lib/semantic_logger/appender/http.rb
lib/semantic_logger/appender/new_relic_logs.rb
lib/semantic_logger/formatters.rb
lib/semantic_logger/formatters/new_relic_logs.rb
test/appender/http_test.rb
test/appender/new_relic_logs_test.rb
test/appender/new_relic_test.rb
test/formatters/new_relic_logs_test.rb
test/logger_test.rb
test/mocks/newrelic_rpm.rb
test/test_helper.rb

- Implement a Formatter for NewRelic logs
- Implement an Appender for NewRelic logs
- Add new methods to mocks to support the above
-  Should I include parameters such as thread name also as custom parameter, or will including it in the NR envelope suffice?
- `Appender::NewRelic`'s test asserts that metrics should not be sent, must this be the same for logs? 
- The mock I did inside the `Appender::NewRelicLogs` does not currently stub out the NR code, this might be an issue as the code inside `AppenderNewRelic.log_newrelic` is not being excercised, should I change this

Implement NewRelic Log Formatter & Appender

---

.github/workflows/ci.yml
CHANGELOG.md

The unquoted 3.0 in the CI configuration gets truncated to '3', and causes the latest Ruby 3 to be loaded.  That's a 3.1 version at this time.  This can be seen below:
As the intention of this entry is to load a 3.0.x Ruby, this is a bug.  
Quote 3.0 in CI configuration to prevent truncation.
Quoting the 3.0 ensures that a Ruby 3.0.x version is loaded for that entry in the CI matrix.

Add Ruby 3.2 and quote 3.0 in CI configuration so it is not truncated to 3

---

CHANGELOG.md
lib/semantic_logger/appender/http.rb
test/appender/http_test.rb

Updated.
Add support for custom headers in HTTP appender. Among other things, this makes it possible to use the HTTP appender with endpoints that use [Bearer auth](https://datatracker.ietf.org/doc/html/rfc6750), like [Logtail's REST API](https://betterstack.com/docs/logs/http-rest-api/).

Add support for custom headers in HTTP appender

---

CHANGELOG.md
lib/semantic_logger/appender/elasticsearch.rb
lib/semantic_logger/appender/elasticsearch_http.rb
test/appender/elasticsearch_test.rb

Adds support for newer versions of Elasticsearch that removed _type in Elasticsearch Appender.
Hi @reidmorrison,
I tested this code with 6.x, 7.x and 8.x. For integrating the tests with the different versions, I think we would need to add different gemfiles and run the tests with each version, but I don't know if that's worth it or something you'd like to have since it'd be quite an overhead. Let me know.
I added a helper function to the tests. For versions < 8.0.0, `Elasticsearch::Transport::Client` and `Elasticsearch::Client` could be used to call `bulk`, but since we extracted Transport into its own library, you need to call `Elasticsearch::Client` for bulk.
Let me know what you think. For `ElasticsearchHTTP`, you'd need to make a call to `/` in the Elasticsearch instance to find out …

Adds support for newer versions of Elasticsearch that removed _type in Elasticsearch Appender

---

CHANGELOG.md
docs/metrics.md

Replace `SemanticLogger::Metrics` with `SemanticLogger::Metric`
Fixes issue #283
- Fix incorrect metrics usage examples in documentation
The documentation incorrectly states that metrics subscribers can be added via `SemanticLogger::Metrics`. This was added in #35cb18c0 but the code was refactored in #e848e327, causing the documentation to become out of date. This PR fixes the documentation to use `SemanticLogger::Metric` instead.

Fix incorrect metrics usage in documentation

---

CHANGELOG.md
lib/semantic_logger/sync_processor.rb

SyncProcessor#log could be called recursively from an appender like Bugsnag and Sentry.
#281
Allow SyncProcessor to be called from appenders
SyncProcessor#log could be called recursively from an appender like Bugsnag and Sentry. However, SyncProcessor doesn't allow it because it uses Mutex to protect SyncProcessor#log. Here are code snippets to reproduce the Mutex error.
```ruby
require 'semantic_logger/sync'
require 'sentry-ruby'
SemanticLogger.add_appender(appender: :sentry_ruby)
Sentry.init do |config|
config.logger = SemanticLogger[Sentry]
config.background_worker_threads = 0
config.dsn = 'http://foo@localhost/bar'
end
logger = SemanticLogger['MyClass']
begin
raise 'something went wrong'
rescue => e
logger.error('oops', e)
end
```
```ruby
require 'semantic_logger/sync'
require …
```

Allow SyncProcessor to be called from appenders

---

lib/semantic_logger/log.rb

Handle a stack trace that does not return a known file and line number #285

---

CHANGELOG.md
lib/semantic_logger/formatters/logfmt.rb

Add :duration_ms to Logfmt formatter
Log processors sometimes parse duration_human as string (because of the added 'ms') which is not always useful.

Add duration and duration_ms for logfmt format

---

CHANGELOG.md
lib/semantic_logger/appenders.rb
test/appenders_test.rb

- Fix regression in `SemanticLogger::Appenders#close`
Backported (from v5) changes to `#close` track list of closed appenders. Unfortunately, the variable name used for tracking is `closed_appenders`, while in the loop we're trying to add the closed appender into non-existing variable `appenders`.
This patch fixes the issue. Also, I moved `closed_appenders << appender` after the fact of closure, so that the returned list is correct in case of either `flush` or `close` failed.
---
Closes: https://github.com/reidmorrison/semantic_logger/issues/291
---

fix: Use correct varname for closed appenders

---

CHANGELOG.md
docs/appenders.md

Add Honeybadger and Honeybadger Insights to Appenders doc

---

CHANGELOG.md
semantic_logger.gemspec

There was a missing `v` before the interpolated version number causing links published on RubyGems.org to 404.

Correct `source_code_uri` URL

---

.dockerignore
CHANGELOG.md
Dockerfile
docker-compose.yaml
lib/semantic_logger/appender/new_relic_logs.rb
lib/semantic_logger/formatters/new_relic_logs.rb
test/appender/new_relic_logs_test.rb
test/formatters/new_relic_logs_test.rb

https://github.com/reidmorrison/semantic_logger/issues/300
Changelog updated appropriately. 
Content below
```
- NR Integration: Ensures key/values are not nested under `messages`
- NR Integration: Ensures structures are built for all nested json (I.E build an actual object instead of doing `span.id` as the key)
- NR Integration: Named tags will instead be added directly to the JSON.  `named_tags` now adds key value pairs to object instead of nesting.  
- NR Integration: Conflicts between `named_tags` and existing tags are logged to `named_tag_conflicts` key.
- NR Integration: Adds a quick and hacky Dockerfile and Docker Compose file to allow for testing changes locally.
```
This PR fixes the NR Log Formatter so that keys are no longer erroneously nested under the `message.` key as …

Newrelic Logs Integration: Unnest messages/named_tags, leverage nested objects, quick hacky Dockerfile

---

.github/workflows/ci.yml
test/formatters/default_test.rb

This PR adds Ruby 3.4 to the CI matrix to confirm Semantic Logger works with Ruby 3.4.
In Ruby 3.4,  the result of `Hash.inspect` has changed. So I updated some specs to wrap hash with `#{}` to work both 3.4 and older.
Ref: https://bugs.ruby-lang.org/issues/20433

CI against Ruby 3.4

---

docs/customize.md

Fix some invalid example code in the docs.
I'm unsure on whether you want this added to the changelog. Assuming no, since it's only docs, and doesn't require a release. Let me know if my assumption is wrong.

Docs: fix example custom formatter

---

CHANGELOG.md
Gemfile
README.md
docs/appenders.md
lib/semantic_logger/appender.rb
lib/semantic_logger/appender/cloudwatch_logs.rb
test/appender/cloudwatch_logs_test.rb

- Add appender for CloudWatch Logs
We've been using CloudWatch Logs for our rails application at @viaeurope and decided to upstream the changes. Since AWS CloudWatch Logs are one of the popular and cheaper logs aggregation services, we thought this might be useful for others too.
Settings for the appender and their default values are mainly inspired by https://docs.docker.com/engine/logging/drivers/awslogs/.
Please let me know if I missed anything as part of this pull request.

Add appender for CloudWatch Logs
